package presentation;

import domain.Controller;
import domain.FacilityBooking;
import domain.GuiLogic;
import domain.QueueEntry;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class OwnBookings extends javax.swing.JFrame {

    private Controller control = Controller.getInstance();
    private DefaultTableModel model;
    private List<FacilityBooking> listOfBookings;
    private SportsFacilitySchedule sportsFacilitySchedule;
    private GuiLogic logic;

    /**
     * Creates new form OwnBookings
     */
    public OwnBookings() {
        constructor();
    }

    public OwnBookings(SportsFacilitySchedule sportsFacilitySchedule) {
        constructor();
        this.sportsFacilitySchedule = sportsFacilitySchedule;
    }

    private void constructor(){
        initComponents();
        logic = GuiLogic.getInstance();
        model = (DefaultTableModel) bookingsTable.getModel();
        initTable();
    }
    
    private void initTable() {
        logic.initOwnBookingTable(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookingsTable = new javax.swing.JTable();
        cancelBookingButton = new javax.swing.JButton();
        backToFacilityBookingsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Facility", "Date", "Timeslot"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookingsTable);

        cancelBookingButton.setText("Cancel Booking");
        cancelBookingButton.setToolTipText("Cancel the selected booking.");
        cancelBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingButtonActionPerformed(evt);
            }
        });

        backToFacilityBookingsButton.setText("Back To Facility Bookings");
        backToFacilityBookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToFacilityBookingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backToFacilityBookingsButton)
                .addGap(18, 18, 18)
                .addComponent(cancelBookingButton)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBookingButton)
                    .addComponent(backToFacilityBookingsButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingButtonActionPerformed
        int bookingID = logic.getListOfBookings().get(bookingsTable.getSelectedRow()).getID();
        List<QueueEntry> q = control.getQueueEntriesOfSpecificBooking(bookingID);
        FacilityBooking fb = control.getFacilityBookingOfSpecificID(bookingID);
        if (q.isEmpty()){
            control.removeFacilityBooking(bookingID);
        } else {
            int newUserID = control.popUserFromQueueForID(bookingID);
            control.updateFacilityBookingUserID(bookingID, newUserID);
        }
        control.createNortificationForCanceledEvent(fb);
        initTable();
    }//GEN-LAST:event_cancelBookingButtonActionPerformed

    private void backToFacilityBookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToFacilityBookingsButtonActionPerformed
        sportsFacilitySchedule.refreshAll();
        sportsFacilitySchedule.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToFacilityBookingsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnBookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToFacilityBookingsButton;
    private javax.swing.JTable bookingsTable;
    private javax.swing.JButton cancelBookingButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
